sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 23uk00OqwUcWZcaNNWce6yhzj9ZiLKGMmxGflUNql4W9QHGvmFiwDmJ+QyYFjWZutu+zZ+wT5sePIsnv/NVJfA+Bt+y4jkoRlM+t2OlO7hz3llzDDwA2PiI6GJaNoVtym542la6ggrGfG4R6Pjzp/aXVgy72UpKVl5RwkB39F5Kyob3JLvC9TnJ+pptD7uo8sd+8Bi53xs6B51piNmZQ+qlHg39qKTcu5eOoMxpkipMtRkWPXJvgZgxQCd37KVrCDydgzudoGwA6q1oWoYVDElG76MHeNFSez+3dLoYxneb63XTRijpffGEtZqXpr7TfY0WWvPP5RgRztIX5pJOjdP1OO2I2gX3q6fF2hsthY3z/FtVIbEJ6Es+rDc2huNZ1YpgGEE7Yry3dVYVymb9pS5Nid2fBF22fP2VKaPrnx1TIDi0DwgsyDIy8ZNgbKiIXut13B998ut6hShyscWhGS8dEg9cFwU8PIQJLmQIHRpWHYMU+eJqRTHa2xZx2WOHVp4ZO5Uq+w/MqoeF4z8/mFEzns2/aqb4iKr7XJQ1qUrTujXaqgqcbHxLgJp0DV62V8pUuHNNUDU9FlMDPCBAglLJM/WxPgDbOtpvamjAc7SQchIUxlyD683kYUUSXmrMHxAbUAToyE6O1yFCY12rDjfs1pOV6SusGKX/jltZrYyY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Memoirs-of-Napoleon-Bonaparte-Volume-08_3558
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy